<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ArkiWeb" nsURI="http:///ArkiWeb.ecore" nsPrefix="ArkiWeb">
  <eClassifiers xsi:type="ecore:EClass" name="ListString">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="List&lt;String>"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListUsuario">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="List&lt;Usuario>"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListPermiso">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="List&lt;Permiso>"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListProyecto">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="List&lt;Proyecto>"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListCertificado">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="List&lt;Certificado>"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListVivienda">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="List&lt;Vivienda>"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListInmueble">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="List&lt;Inmueble>"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListCertificados_Asignados">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="List&lt;Certificados_Asignados>"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListProyectos_Asignados">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="List&lt;Proyectos_Asignados>"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListProyectos_En_Ejecucion">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="List&lt;Proyectos_En_Ejecucion>"/>
    </eAnnotations>
  </eClassifiers>
  <eSubpackages name="modelo" nsURI="http:///ArkiWeb/modelo.ecore" nsPrefix="ArkiWeb.modelo">
    <eClassifiers xsi:type="ecore:EClass" name="Permiso" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_permiso" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_rol" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="objeto_permiso" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lectura_permiso" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="escritura_permiso" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rol" ordered="false"
          lowerBound="1" eType="#//modelo/Rol"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Rol" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_rol" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="descripcion_rol" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Usuario" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_usuario" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre_usuario" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="apellidos_usuario" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dni_usuario" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="telefono_usuario" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="email_usuario" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="domicilio_usuario" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="contrasenya_usuario"
          ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rol_usuario" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rol" ordered="false"
          lowerBound="1" eType="#//modelo/Rol"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Proyecto" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_proyecto" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="descripcion_proyecto"
          ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_cliente_proyecto"
          ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_vivienda_proyecto"
          ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_inmueble_proyecto"
          ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo_proyecto" ordered="false"
          lowerBound="1" eType="#//modelo/Tipo_Proyecto"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fecha_solicitud_proyecto"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fecha_entrega_proyecto"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="duracion_prevista_proyecto"
          ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="presupuesto_ejecucion_proyecto"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="usuario" ordered="false"
          eType="#//modelo/Usuario"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="vivienda" ordered="false"
          eType="#//modelo/Vivienda"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inmueble" ordered="false"
          eType="#//modelo/Inmueble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="superficie_proyecto"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="coste_proyecto" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Tipo_Proyecto">
      <eLiterals name="Residencial_Edificio"/>
      <eLiterals name="Residencial_Vivienda" value="1"/>
      <eLiterals name="No_Residencial" value="2"/>
      <eLiterals name="Rehabilitacion" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Vivienda" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_vivienda" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="descripcion_vivienda"
          ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="direccion_vivienda" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_inmueble_vivienda"
          ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="superficie_terreno_vivienda"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="superficie_vivienda"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="plantas_vivienda" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="habitaciones_vivienda"
          ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="banyos_vivienda" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Inmueble" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="vivienda" ordered="false"
          upperBound="-1" eType="#//modelo/Vivienda" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_inmueble" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="descripcion_inmueble"
          ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="direccion_inmueble" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="superficie_terreno_inmueble"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="superficie_inmueble"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Certificado" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_certificado" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="descripcion_certificado"
          ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_cliente_certificado"
          ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_vivienda_certificado"
          ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_inmueble_certificado"
          ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo_certificado" ordered="false"
          lowerBound="1" eType="#//modelo/Tipo_Certificado"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fecha_solicitud_certificado"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fecha_entrega_certificado"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fecha_visita_certificado"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fecha_emision_certificado"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="categoria_certificado"
          ordered="false" lowerBound="1" eType="#//modelo/Categoria_Certificado"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_arquitecto_certificado"
          ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="coste_certificado" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inmueble" ordered="false"
          lowerBound="1" eType="#//modelo/Inmueble"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="usuario" ordered="false"
          eType="#//modelo/Usuario"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="vivienda" ordered="false"
          eType="#//modelo/Vivienda"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Tipo_Certificado">
      <eLiterals name="Habitabilidad"/>
      <eLiterals name="ITE" value="1"/>
      <eLiterals name="Efic_Energ" value="2"/>
      <eLiterals name="Pericial" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Categoria_Certificado">
      <eLiterals name="A"/>
      <eLiterals name="B" value="1"/>
      <eLiterals name="C" value="2"/>
      <eLiterals name="D" value="3"/>
      <eLiterals name="E" value="4"/>
      <eLiterals name="F" value="5"/>
      <eLiterals name="G" value="6"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HSQLDB" abstract="true" interface="true">
      <eOperations name="crearUsuario" ordered="false" lowerBound="1">
        <eParameters name="ususario" ordered="false" lowerBound="1" eType="#//modelo/Usuario"/>
      </eOperations>
      <eOperations name="editarUsuario" ordered="false" lowerBound="1">
        <eParameters name="usuario" ordered="false" lowerBound="1" eType="#//modelo/Usuario"/>
      </eOperations>
      <eOperations name="bajaUsuario" ordered="false" lowerBound="1">
        <eParameters name="id_usuario" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="crearPermiso" ordered="false" lowerBound="1">
        <eParameters name="permiso" ordered="false" lowerBound="1" eType="#//modelo/Permiso"/>
      </eOperations>
      <eOperations name="editarPermiso" ordered="false" lowerBound="1">
        <eParameters name="permiso" ordered="false" lowerBound="1" eType="#//modelo/Permiso"/>
      </eOperations>
      <eOperations name="crearCertificado" ordered="false" lowerBound="1">
        <eParameters name="certificado" ordered="false" lowerBound="1" eType="#//modelo/Certificado"/>
      </eOperations>
      <eOperations name="editarCertificado" ordered="false" lowerBound="1">
        <eParameters name="certificado" ordered="false" lowerBound="1" eType="#//modelo/Certificado"/>
      </eOperations>
      <eOperations name="buscarCertificado" ordered="false" lowerBound="1" eType="#//modelo/Certificado">
        <eParameters name="id_certificado" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="crearProyecto" ordered="false" lowerBound="1">
        <eParameters name="proyecto" ordered="false" lowerBound="1" eType="#//modelo/Proyecto"/>
      </eOperations>
      <eOperations name="editarProyecto" ordered="false" lowerBound="1">
        <eParameters name="proyecto" ordered="false" lowerBound="1" eType="#//modelo/Proyecto"/>
      </eOperations>
      <eOperations name="buscarProyecto" ordered="false" lowerBound="1" eType="#//modelo/Proyecto">
        <eParameters name="id_proyecto" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="crearVivienda" ordered="false" lowerBound="1">
        <eParameters name="vivienda" ordered="false" lowerBound="1" eType="#//modelo/Vivienda"/>
      </eOperations>
      <eOperations name="editarVivienda" ordered="false" lowerBound="1">
        <eParameters name="vivienda" ordered="false" lowerBound="1" eType="#//modelo/Vivienda"/>
      </eOperations>
      <eOperations name="buscarVivienda" ordered="false" lowerBound="1" eType="#//modelo/Vivienda">
        <eParameters name="id_vivienda" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="crearInmueble" ordered="false" lowerBound="1">
        <eParameters name="inmueble" ordered="false" lowerBound="1" eType="#//modelo/Inmueble"/>
      </eOperations>
      <eOperations name="editarInmueble" ordered="false" lowerBound="1">
        <eParameters name="inmueble" ordered="false" lowerBound="1" eType="#//modelo/Inmueble"/>
      </eOperations>
      <eOperations name="buscarInmueble" ordered="false" lowerBound="1" eType="#//modelo/Inmueble">
        <eParameters name="id_inmueble" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="asignarCertificado" ordered="false" lowerBound="1">
        <eParameters name="asignacionCertificado" ordered="false" lowerBound="1" eType="#//modelo/Certificados_Asignados"/>
      </eOperations>
      <eOperations name="editarAsignacionCertificado" ordered="false" lowerBound="1">
        <eParameters name="asignacionCertificado" ordered="false" lowerBound="1" eType="#//modelo/Certificados_Asignados"/>
      </eOperations>
      <eOperations name="asignarProyecto" ordered="false" lowerBound="1">
        <eParameters name="proyectoAsignado" ordered="false" lowerBound="1" eType="#//modelo/Proyectos_Asignados"/>
      </eOperations>
      <eOperations name="editarAsignacionProyecto" ordered="false" lowerBound="1">
        <eParameters name="proyectoAsignado" ordered="false" lowerBound="1" eType="#//modelo/Proyectos_Asignados"/>
      </eOperations>
      <eOperations name="contratarProyecto" ordered="false" lowerBound="1">
        <eParameters name="contratacionProyecto" ordered="false" lowerBound="1" eType="#//modelo/Proyectos_En_Ejecucion"/>
      </eOperations>
      <eOperations name="editarContratacionProyecto" ordered="false" lowerBound="1">
        <eParameters name="contratacionProyecto" ordered="false" lowerBound="1" eType="#//modelo/Proyectos_En_Ejecucion"/>
      </eOperations>
      <eOperations name="queryCrear" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String">
        <eParameters name="tabla" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="columnas" ordered="false" lowerBound="1" eType="#//ListString"/>
        <eParameters name="valores_columnas" ordered="false" lowerBound="1" eType="#//ListString"/>
      </eOperations>
      <eOperations name="queryEditar" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String">
        <eParameters name="tabla" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="columnas" ordered="false" lowerBound="1" eType="#//ListString"/>
        <eParameters name="valores_columnas" ordered="false" lowerBound="1" eType="#//ListString"/>
        <eParameters name="where_clause" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="queryBuscar" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String">
        <eParameters name="tabla" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="columnas" ordered="false" lowerBound="1" eType="#//ListString"/>
        <eParameters name="where_clause_01" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="queryEjecutar" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
        <eParameters name="queryString" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Certificados_Asignados" abstract="true"
        interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_proyecto_asignado"
          ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="id_proyecto_proyecto_asignado"
          ordered="false" lowerBound="1" eType="#//modelo/Proyecto"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="id_arquitecto_proyecto_asignado"
          ordered="false" lowerBound="1" eType="#//modelo/Usuario"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_certificado_asignado"
          ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_certificado_certificado_asignado"
          ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_arquitecto_certificado_asignado"
          ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="certificado" ordered="false"
          lowerBound="1" eType="#//modelo/Certificado"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="usuario" ordered="false"
          lowerBound="1" eType="#//modelo/Usuario"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Proyectos_Asignados" abstract="true"
        interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_proyecto_asignado"
          ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_proyecto_proyecto_asignado"
          ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_arquitecto_proyecto_asignado"
          ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="proyecto" ordered="false"
          lowerBound="1" eType="#//modelo/Proyecto"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="usuario" ordered="false"
          lowerBound="1" eType="#//modelo/Usuario"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Proyectos_En_Ejecucion" abstract="true"
        interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_ejecucion_proyecto"
          ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_proyecto_ejecucion_proyecto"
          ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fecha_inicio_ejecucion_proyecto"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="duracion_prevista_ejecucion_proyecto"
          ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fecha_fin_ejecucion_proyecto"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="proyecto" ordered="false"
          lowerBound="1" eType="#//modelo/Proyecto"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Factory">
      <eOperations name="crearObjeto" ordered="false" lowerBound="1">
        <eParameters name="tipoObjeto" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="_" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConcreteFactory" eSuperTypes="#//modelo/Factory"/>
  </eSubpackages>
  <eSubpackages name="vista" nsURI="http:///ArkiWeb/vista.ecore" nsPrefix="ArkiWeb.vista">
    <eSubpackages name="struts2mvc" nsURI="http:///ArkiWeb/vista/struts2mvc.ecore"
        nsPrefix="ArkiWeb.vista.struts2mvc">
      <eSubpackages name="modelo" nsURI="http:///ArkiWeb/vista/struts2mvc/modelo.ecore"
          nsPrefix="ArkiWeb.vista.struts2mvc.modelo">
        <eClassifiers xsi:type="ecore:EClass" name="LoginActionSupport">
          <eOperations name="execute" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="AltaUsuarioActionSupport">
          <eOperations name="execute" ordered="false" lowerBound="1"/>
          <eOperations name="execute" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="PortalClienteActionSupport">
          <eOperations name="execute" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="PortalAdministradorActionSupport">
          <eOperations name="execute" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="PortalArquitectoActionSupport">
          <eOperations name="execute" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="EditarUsuarioActionSupport">
          <eOperations name="execute" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="EditarPermisoActionSupport">
          <eOperations name="execute" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="EditarCertificadoActionSupport">
          <eOperations name="execute" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="EditarProyectoActionSupport">
          <eOperations name="execute" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="EditarEjecucionProyectoActionSupport">
          <eOperations name="execute" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        </eClassifiers>
      </eSubpackages>
      <eSubpackages name="controlador" nsURI="http:///ArkiWeb/vista/struts2mvc/controlador.ecore"
          nsPrefix="ArkiWeb.vista.struts2mvc.controlador"/>
      <eSubpackages name="vista" nsURI="http:///ArkiWeb/vista/struts2mvc/vista.ecore"
          nsPrefix="ArkiWeb.vista.struts2mvc.vista"/>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="controlador" nsURI="http:///ArkiWeb/controlador.ecore" nsPrefix="ArkiWeb.controlador">
    <eClassifiers xsi:type="ecore:EClass" name="Controlador_Modelo" abstract="true"
        interface="true">
      <eOperations name="crearUsuario" ordered="false" lowerBound="1">
        <eParameters name="usuario" ordered="false" lowerBound="1" eType="#//modelo/Usuario"/>
      </eOperations>
      <eOperations name="editarUsuario" ordered="false" lowerBound="1">
        <eParameters name="usuario" ordered="false" lowerBound="1" eType="#//modelo/Usuario"/>
      </eOperations>
      <eOperations name="bajaUsuario" ordered="false" lowerBound="1" eType="#//modelo/Usuario">
        <eParameters name="id_usuario" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="crearPermiso" ordered="false" lowerBound="1">
        <eParameters name="permiso" ordered="false" lowerBound="1" eType="#//modelo/Permiso"/>
      </eOperations>
      <eOperations name="editarPermiso" ordered="false" lowerBound="1">
        <eParameters name="permiso" ordered="false" lowerBound="1" eType="#//modelo/Permiso"/>
      </eOperations>
      <eOperations name="crearCertificado" ordered="false" lowerBound="1">
        <eParameters name="certificado" ordered="false" lowerBound="1" eType="#//modelo/Certificado"/>
      </eOperations>
      <eOperations name="editarCertificado" ordered="false" lowerBound="1">
        <eParameters name="certificado" ordered="false" lowerBound="1" eType="#//modelo/Certificado"/>
      </eOperations>
      <eOperations name="buscarCertificado" ordered="false" lowerBound="1" eType="#//modelo/Certificado">
        <eParameters name="id_certificado" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="crearProyecto" ordered="false" lowerBound="1">
        <eParameters name="proyecto" ordered="false" lowerBound="1" eType="#//modelo/Proyecto"/>
      </eOperations>
      <eOperations name="editarProyecto" ordered="false" lowerBound="1">
        <eParameters name="proyecto" ordered="false" lowerBound="1" eType="#//modelo/Proyecto"/>
      </eOperations>
      <eOperations name="buscarProyecto" ordered="false" lowerBound="1" eType="#//modelo/Proyecto">
        <eParameters name="id_proyecto" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="crearVivienda" ordered="false" lowerBound="1">
        <eParameters name="vivienda" ordered="false" lowerBound="1" eType="#//modelo/Vivienda"/>
      </eOperations>
      <eOperations name="editarVivienda" ordered="false" lowerBound="1">
        <eParameters name="vivienda" ordered="false" lowerBound="1" eType="#//modelo/Vivienda"/>
      </eOperations>
      <eOperations name="buscarVivienda" ordered="false" lowerBound="1" eType="#//modelo/Vivienda">
        <eParameters name="id_vivienda" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="crearInmueble" ordered="false" lowerBound="1">
        <eParameters name="inmueble" ordered="false" lowerBound="1" eType="#//modelo/Inmueble"/>
      </eOperations>
      <eOperations name="editarInmueble" ordered="false" lowerBound="1">
        <eParameters name="inmueble" ordered="false" lowerBound="1" eType="#//modelo/Inmueble"/>
      </eOperations>
      <eOperations name="buscarInmueble" ordered="false" lowerBound="1" eType="#//modelo/Inmueble">
        <eParameters name="id_inmueble" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="asignarCertificado" ordered="false" lowerBound="1">
        <eParameters name="asignacionCertificado" ordered="false" lowerBound="1" eType="#//modelo/Certificados_Asignados"/>
      </eOperations>
      <eOperations name="editarAsignacionCertificado" ordered="false" lowerBound="1">
        <eParameters name="asignacionCertificado" ordered="false" lowerBound="1" eType="#//modelo/Certificados_Asignados"/>
      </eOperations>
      <eOperations name="asignarProyecto" ordered="false" lowerBound="1">
        <eParameters name="asignacionProyecto" ordered="false" lowerBound="1" eType="#//modelo/Proyectos_Asignados"/>
      </eOperations>
      <eOperations name="editarAsignacionProyecto" ordered="false" lowerBound="1">
        <eParameters name="asignacionProyecto" ordered="false" lowerBound="1" eType="#//modelo/Proyectos_Asignados"/>
      </eOperations>
      <eOperations name="contratarProyecto" ordered="false" lowerBound="1">
        <eParameters name="contratacionProyecto" ordered="false" lowerBound="1" eType="#//modelo/Proyectos_En_Ejecucion"/>
      </eOperations>
      <eOperations name="editarContratacionProyecto" ordered="false" lowerBound="1">
        <eParameters name="contratacionProyecto" ordered="false" lowerBound="1" eType="#//modelo/Proyectos_En_Ejecucion"/>
      </eOperations>
      <eOperations name="login" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Boolean">
        <eParameters name="email" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="password" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="cambiarContrasenya" ordered="false" lowerBound="1">
        <eParameters name="email" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="listarUsuarios" ordered="false" lowerBound="1" eType="#//ListUsuario"/>
      <eOperations name="listarPermisos" ordered="false" lowerBound="1" eType="#//ListPermiso"/>
      <eOperations name="listarProyectos" ordered="false" lowerBound="1" eType="#//ListProyecto"/>
      <eOperations name="listarCertificados" ordered="false" lowerBound="1" eType="#//ListCertificado"/>
      <eOperations name="listarViviendas" ordered="false" lowerBound="1" eType="#//ListVivienda"/>
      <eOperations name="listarInmuebles" ordered="false" lowerBound="1" eType="#//ListInmueble"/>
      <eOperations name="buscarUsuario" ordered="false" lowerBound="1" eType="#//modelo/Usuario">
        <eParameters name="id_usuario" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="buscarMisProyectos" ordered="false" lowerBound="1" eType="#//ListProyecto">
        <eParameters name="id_Usuario" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="buscarProyectosPorUsuario" ordered="false" lowerBound="1"
          eType="#//ListProyecto">
        <eParameters name="id_Usuario" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="buscarMisCertificados" ordered="false" lowerBound="1" eType="#//ListCertificado">
        <eParameters name="id_Usuario" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="buscarCertificadosPorUsuario" ordered="false" lowerBound="1"
          eType="#//ListCertificado">
        <eParameters name="id_Usuario" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="buscarCertificadosPorVivienda" ordered="false" lowerBound="1"
          eType="#//ListCertificado">
        <eParameters name="id_vivienda" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="buscarCertificadosPorInmueble" ordered="false" lowerBound="1"
          eType="#//ListCertificado">
        <eParameters name="id_Inmueble" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="buscarCertificadosPorEdadInmueble" ordered="false" lowerBound="1"
          eType="#//ListCertificado">
        <eParameters name="edad" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="buscarCertificadosPorEdadCertificadoHabitabilidad" ordered="false"
          lowerBound="1" eType="#//ListCertificado">
        <eParameters name="edad" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="buscarAsignacionCertificado" ordered="false" lowerBound="1"
          eType="#//modelo/Certificados_Asignados">
        <eParameters name="id_usuario" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
        <eParameters name="id_certificado" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="buscarAsignacionProyecto" ordered="false" lowerBound="1"
          eType="#//modelo/Proyectos_Asignados">
        <eParameters name="id_usuario" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
        <eParameters name="id_proyecto" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="buscarContratacionProyecto" ordered="false" lowerBound="1"
          eType="#//modelo/Proyectos_En_Ejecucion">
        <eParameters name="id_proyecto" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Control_Login" abstract="true" interface="true">
      <eOperations name="login" ordered="false" lowerBound="1">
        <eParameters name="email" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="contrasenya" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="cambiarContrasenya" ordered="false" lowerBound="1">
        <eParameters name="email" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Control_Permisos" abstract="true"
        interface="true">
      <eOperations name="concederAcceso" ordered="false" lowerBound="1"/>
      <eOperations name="crearPermiso" ordered="false" lowerBound="1">
        <eParameters name="permiso" ordered="false" lowerBound="1" eType="#//modelo/Permiso"/>
      </eOperations>
      <eOperations name="editarPermiso" ordered="false" lowerBound="1">
        <eParameters name="permiso" ordered="false" lowerBound="1" eType="#//modelo/Permiso"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Control_Usuarios" abstract="true"
        interface="true">
      <eOperations name="crearUsuario" ordered="false" lowerBound="1">
        <eParameters name="usuario" ordered="false" lowerBound="1" eType="#//modelo/Usuario"/>
      </eOperations>
      <eOperations name="editarUsuario_1" ordered="false" lowerBound="1">
        <eParameters name="usuario" ordered="false" lowerBound="1" eType="#//modelo/Usuario"/>
      </eOperations>
      <eOperations name="bajaUsuario" ordered="false" lowerBound="1">
        <eParameters name="id_Usuario" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Control_Certificados" abstract="true"
        interface="true">
      <eOperations name="editarCertificado" ordered="false" lowerBound="1">
        <eParameters name="certificado" ordered="false" lowerBound="1" eType="#//modelo/Certificado"/>
      </eOperations>
      <eOperations name="asignarCertificado" ordered="false" lowerBound="1">
        <eParameters name="certificado" ordered="false" lowerBound="1" eType="#//modelo/Certificado"/>
      </eOperations>
      <eOperations name="editarAsignacionCertificado" ordered="false" lowerBound="1">
        <eParameters name="certificado" ordered="false" lowerBound="1" eType="#//modelo/Certificado"/>
      </eOperations>
      <eOperations name="crearCertificado" ordered="false" lowerBound="1">
        <eParameters name="certificado" ordered="false" lowerBound="1" eType="#//modelo/Certificado"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Control_Proyectos" abstract="true"
        interface="true">
      <eOperations name="crearProyecto" ordered="false" lowerBound="1">
        <eParameters name="proyecto" ordered="false" lowerBound="1" eType="#//modelo/Proyecto"/>
      </eOperations>
      <eOperations name="editarProyecto" ordered="false" lowerBound="1">
        <eParameters name="proyecto" ordered="false" lowerBound="1" eType="#//modelo/Proyecto"/>
      </eOperations>
      <eOperations name="asignarProyecto" ordered="false" lowerBound="1">
        <eParameters name="asignacionProyecto" ordered="false" lowerBound="1" eType="#//modelo/Proyectos_Asignados"/>
      </eOperations>
      <eOperations name="editarAsignacionProyecto" ordered="false" lowerBound="1">
        <eParameters name="asignacionProyecto" ordered="false" lowerBound="1" eType="#//modelo/Proyectos_Asignados"/>
      </eOperations>
      <eOperations name="contratarProyecto" ordered="false" lowerBound="1">
        <eParameters name="contratacionProyecto" ordered="false" lowerBound="1" eType="#//modelo/Proyectos_En_Ejecucion"/>
      </eOperations>
      <eOperations name="editarContratacionProyecto" ordered="false" lowerBound="1">
        <eParameters name="contratacionProyecto" ordered="false" lowerBound="1" eType="#//modelo/Proyectos_En_Ejecucion"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Control_Viviendas" abstract="true"
        interface="true">
      <eOperations name="crearVivienda" ordered="false" lowerBound="1">
        <eParameters name="vivienda" ordered="false" lowerBound="1" eType="#//modelo/Vivienda"/>
      </eOperations>
      <eOperations name="editarVivienda" ordered="false" lowerBound="1">
        <eParameters name="vivienda" ordered="false" lowerBound="1" eType="#//modelo/Vivienda"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Control_Inmuebles" abstract="true"
        interface="true">
      <eOperations name="crearInmueble" ordered="false" lowerBound="1">
        <eParameters name="inmueble" ordered="false" lowerBound="1" eType="#//modelo/Inmueble"/>
      </eOperations>
      <eOperations name="editarInmueble" ordered="false" lowerBound="1">
        <eParameters name="inmueble" ordered="false" lowerBound="1" eType="#//modelo/Inmueble"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Gestor_Busquedas" abstract="true"
        interface="true">
      <eOperations name="listarUsuarios" ordered="false" lowerBound="1" eType="#//ListUsuario"/>
      <eOperations name="buscarInmueble" ordered="false" lowerBound="1" eType="#//modelo/Inmueble">
        <eParameters name="id_inmueble" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="listarPermisos" ordered="false" lowerBound="1" eType="#//ListPermiso"/>
      <eOperations name="listarProyectos" ordered="false" lowerBound="1" eType="#//ListProyecto"/>
      <eOperations name="listarCertificados" ordered="false" lowerBound="1" eType="#//ListCertificado"/>
      <eOperations name="listarViviendas" ordered="false" lowerBound="1" eType="#//ListVivienda"/>
      <eOperations name="listarInmuebles" ordered="false" lowerBound="1" eType="#//ListInmueble"/>
      <eOperations name="listarPermisosUsuario" ordered="false" lowerBound="1" eType="#//ListPermiso">
        <eParameters name="id_usuario" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="buscarUsuario" ordered="false" lowerBound="1" eType="#//modelo/Usuario">
        <eParameters name="id_usuario" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="buscarVivienda" ordered="false" lowerBound="1" eType="#//modelo/Vivienda">
        <eParameters name="id_vivienda" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="buscarProyecto" ordered="false" lowerBound="1" eType="#//modelo/Proyecto">
        <eParameters name="id_proyecto" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="buscarCertificado" ordered="false" lowerBound="1" eType="#//modelo/Certificado">
        <eParameters name="id_certificado" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="buscarMisProyectos" ordered="false" lowerBound="1" eType="#//ListProyecto">
        <eParameters name="id_usuario" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="buscarProyectosPorUsuario" ordered="false" lowerBound="1"
          eType="#//ListProyecto">
        <eParameters name="id_usuario" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="buscarMisCertificados" ordered="false" lowerBound="1" eType="#//ListCertificado">
        <eParameters name="id_usuario" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="buscarCertificadosPorUsuario" ordered="false" lowerBound="1"
          eType="#//ListCertificado">
        <eParameters name="id_usuario" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="buscarCertificadosPorVivienda" ordered="false" lowerBound="1"
          eType="#//ListCertificado">
        <eParameters name="id_vivienda" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="buscarCertificadosPorInmueble" ordered="false" lowerBound="1"
          eType="#//ListCertificado">
        <eParameters name="id_inmueble" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="buscarCertificadosPorEdadInmueble" ordered="false" lowerBound="1"
          eType="#//ListCertificado">
        <eParameters name="edad" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="buscarCertificadosPorEdadCertificadoHabitabilidad" ordered="false"
          lowerBound="1" eType="#//ListCertificado">
        <eParameters name="edad" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="buscarAsignacionProyecto" ordered="false" lowerBound="1"
          eType="#//modelo/Proyectos_Asignados">
        <eParameters name="id_usuario" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
        <eParameters name="id_proyecto" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="buscarContratacionProyecto" ordered="false" lowerBound="1"
          eType="#//modelo/Proyectos_En_Ejecucion">
        <eParameters name="id_proyecto" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="buscarAsignacionCertificado" ordered="false" lowerBound="1"
          eType="#//ListCertificados_Asignados">
        <eParameters name="id_usuario" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
        <eParameters name="id_certificado" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
